version: 2.1

orbs:
  win: circleci/windows@2.4.1

jobs:
  linux:
    docker:
      - image: ubuntu:rolling

    resource_class: large
    steps:
      - checkout

      - run:
          command: |
            apt-get update
            export DEBIAN_FRONTEND=noninteractive
            apt-get install -q -y curl openjdk-11-jdk patch
            curl -sSL https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-linux-amd64 >/usr/local/bin/bazel
            chmod +x /usr/local/bin/bazel

      - run:
          command: |
            ./exercise.sh

  windows:
    executor:
      name: win/default
      shell: powershell.exe
      size: large
    steps:
      - checkout
      - run: systeminfo

      - run:
          shell: cmd.exe
          command: |
            curl -sSL https://releases.bazel.build/5.1.0/rc3/bazel-5.1.0rc3-windows-x86_64.exe >/ProgramData/nvm/bazel.exe

      - run:
          command: |
            bazel build ...
            bazel test ... --test_verbose_timeout_warnings --test_output=errors
            bazel run :hello-world
            bazel run //app-one/src/main/java/com/example/myproject:hello-world
            bazel run //app-one/src/main/java/com/example/myproject:hello-data

workflows:
  version: 2
  both_platforms:
    jobs:
      - linux
      - windows
